---
output:
  pdf_document: default
  html_document: default
---
Question 7
```{r}
# load the default data
library(ISLR2)
data(Default) 
```

```{r}
Default <- na.omit(Default)
n <- nrow(Default)
set.seed(123)
ntest <- trunc(n / 3)
testid <- sample(1:n, ntest)
```

```{r}
# fit linear logistic regression, and calculate the accuracy
lfit <- glm(default ~ ., 
            data = Default[-testid, ], 
            family = binomial)

prob <- predict(lfit, Default[testid, ], type = "response")

pred <- ifelse(prob > 0.5, "Yes", "No")

mean(pred == Default$default[testid])
```

```{r}
# fit neural network
# first, scale model matrix
x <- scale(model.matrix(default ~ . -1, data = Default))
y <- ifelse(Default$default=="Yes", 1, 0)
```

```{r}
# second, fit a neural network
library(keras3)
modnn <- keras_model_sequential () %>%
 layer_dense(units = 10, activation = "relu",input_shape = ncol(x)) %>%
 layer_dropout(rate = 0.4) %>%
 layer_dense(units = 1, activation = "sigmoid")
```

```{r}
# third, compile
modnn %>% compile(
  optimizer = "adam",
  loss = "binary_crossentropy",
  metrics = "accuracy"
)
```

```{r}
# fourth, generate history
history <- modnn %>% fit(
  x[-testid, ], y[-testid],
  epochs = 50,
  batch_size = 128,
  validation_data = list(x[testid, ], y[testid]))
plot(history)
```

```{r}
# fifth, calculate accuracy
prob_nn <- modnn %>% predict(x[testid, ])
pred_nn <- ifelse(prob_nn > 0.5, 1, 0)

mean(pred_nn == y[testid])
```

Conclusions: by accuracy, the logistic regression (0.972) is slightly better than the neural network (0.966).




Question 8
```{r}
# first, load the pretrained model
model <- application_resnet50(weights = "imagenet")
```

```{r}
# second, load my animals
img_dir <- "/Users/luqiwang/Documents/GitHub/ECL298_2026/Deep_learning/my_animals"
image_names <- list.files(img_dir)
num_images <- length(image_names)
```

```{r}
# create input matrix
x <- array(dim = c(num_images , 224, 224, 3))

for (i in 1:num_images) {
  img_path <- paste(img_dir, image_names[i], sep = "/")
  img <- image_load(img_path, target_size = c(224, 224))
  x[i,,, ] <- image_to_array(img)
}
x <- imagenet_preprocess_input(x)
```

```{r}
# predict
pred10 <- model %>% predict(x) %>% imagenet_decode_predictions (top = 5)
```

```{r}
# report the classification and probability
for (i in seq_along(pred10)) {
  cat("\n--------------------------------\n")
  cat("Image:", image_names[i], "\n")
  print(pred10[[i]][, c("class_description", "score")])
}
```

